// Login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

//investorType
export const INVESTOR_TYPE_REQUEST = 'INVESTOR_TYPE_REQUEST';
export const INVESTOR_TYPE_SUCCESS = 'INVESTOR_TYPE_SUCCESS';
export const INVESTOR_TYPE_FAILED = 'INVESTOR_TYPE_FAILED';