// Login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

//Prefix
export const FREFIX_REQUEST = 'FREFIX_REQUEST';
export const FREFIX_SUCCESS = 'FREFIX_SUCCESS';
export const FREFIX_FAILED = 'FREFIX_FAILED';

//Company
export const COMPANY_REQUEST = 'COMPANY_REQUEST';
export const COMPANY_SUCCESS = 'COMPANY_SUCCESS';
export const COMPANY_FAILED = 'COMPANY_FAILED';

//ensureAsset
export const ENSURE_ASSET_REQUEST = 'ENSURE_ASSET_REQUEST';
export const ENSURE_ASSET_SUCCESS = 'ENSURE_ASSET_SUCCESS';
export const ENSURE_ASSET_FAILED = 'ENSURE_ASSET_FAILED';

//investorType
export const INVESTOR_TYPE_REQUEST = 'INVESTOR_TYPE_REQUEST';
export const INVESTOR_TYPE_SUCCESS = 'INVESTOR_TYPE_SUCCESS';
export const INVESTOR_TYPE_FAILED = 'INVESTOR_TYPE_FAILED';

//contractVcsc
export const CONTRACT_VCSC_REQUEST = 'CONTRACT_VCSC_REQUEST';
export const CONTRACT_VCSC_SUCCESS = 'CONTRACT_VCSC_SUCCESS';
export const CONTRACT_VCSC_FAILED = 'CONTRACT_VCSC_FAILED';

//branchVCSC
export const BRANCH_VCSC_REQUEST = 'BRANCH_VCSC_REQUEST';
export const BRANCH_VCSC_SUCCESS = 'BRANCH_VCSC_SUCCESS';
export const BRANCH_VCSC_FAILED = 'BRANCH_VCSC_FAILED';

//dayInterestYear
export const DAY_INTEREST_YEAR_REQUEST = 'DAY_INTEREST_YEAR_REQUEST';
export const DAY_INTEREST_YEAR_SUCCESS = 'DAY_INTEREST_YEAR_SUCCESS';
export const DAY_INTEREST_YEAR_FAILED = 'DAY_INTEREST_YEAR_FAILED';

//paymentTerm
export const PAYMENT_TERM_REQUEST = 'PAYMENT_TERM_REQUEST';
export const PAYMENT_TERM_SUCCESS = 'PAYMENT_TERM_SUCCESS';
export const PAYMENT_TERM_FAILED = 'PAYMENT_TERM_FAILED';

//bondType
export const BOND_TYPE_REQUEST = 'BOND_TYPE_REQUEST';
export const BOND_TYPE_SUCCESS = 'BOND_TYPE_SUCCESS';
export const BOND_TYPE_FAILED = 'BOND_TYPE_FAILED';


//bondAsset
export const BONDS_ASSET_REQUEST = 'BONDS_ASSET_REQUEST';
export const BONDS_ASSET_SUCCESS = 'BONDS_ASSET_SUCCESS';
export const BONDS_ASSET_FAILED = 'BONDS_ASSET_FAILED';

//interestRate
export const INTEREST_RATE_REQUEST = 'INTEREST_RATE_REQUEST';
export const INTEREST_RATE_SUCCESS = 'INTEREST_RATE_SUCCESS';
export const INTEREST_RATE_FAILED = 'INTEREST_RATE_FAILED';

//bondPrice
export const BOND_PRICE_REQUEST = 'BOND_PRICE_REQUEST';
export const BOND_PRICE_SUCCESS = 'BOND_PRICE_SUCCESS';
export const BOND_PRICE_FAILED = 'BOND_PRICE_FAILED';

//roomVCSC
export const ROOM_VCSC_REQUEST = 'ROOM_VCSC_REQUEST';
export const ROOM_VCSC_SUCCESS = 'ROOM_VCSC_SUCCESS';
export const ROOM_VCSC_FAILED = 'ROOM_VCSC_FAILED';